[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.attack_damage"
        operation = "add"
        amount = 1.0
    [[effects.conditions]]
        groups = ["proteins"]
        match = "all"
        above = 0.4
        below = 0.6
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.attack_damage"
        operation = "add"
        amount = 1.5
    [[effects.conditions]]
        groups = ["proteins"]
        match = "all"
        above = 0.6
        below = 0.8
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.attack_damage"
        operation = "add"
        amount = 2.0
    [[effects.conditions]]
        groups = ["proteins"]
        match = "all"
        above = 0.8
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.attack_speed"
        operation = "add"
        amount = 0.1
    [[effects.conditions]]
        groups = ["grains"]
        match = "all"
        above = 0.4
        below = 0.6
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.attack_speed"
        operation = "add"
        amount = 0.15
    [[effects.conditions]]
        groups = ["grains"]
        match = "all"
        above = 0.6
        below = 0.8
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.attack_speed"
        operation = "add"
        amount = 0.2
    [[effects.conditions]]
        groups = ["grains"]
        match = "all"
        above = 0.8
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.armor_toughness"
        operation = "add"
        amount = 1.0
    [[effects.conditions]]
        groups = ["fruits"]
        match = "all"
        above = 0.4
        below = 0.6
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.armor_toughness"
        operation = "add"
        amount = 2.0
    [[effects.conditions]]
        groups = ["fruits"]
        match = "all"
        above = 0.6
        below = 0.8
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.armor_toughness"
        operation = "add"
        amount = 3.0
    [[effects.conditions]]
        groups = ["fruits"]
        match = "all"
        above = 0.8
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.armor"
        operation = "add"
        amount = 1.0
    [[effects.conditions]]
        groups = ["vegetables"]
        match = "all"
        above = 0.4
        below = 0.6
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.armor"
        operation = "add"
        amount = 2.5
    [[effects.conditions]]
        groups = ["vegetables"]
        match = "all"
        above = 0.6
        below = 0.8
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.armor"
        operation = "add"
        amount = 4.0
    [[effects.conditions]]
        groups = ["vegetables"]
        match = "all"
        above = 0.8
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 1.0
    [[effects.conditions]]
        groups = ["sugars"]
        match = "all"
        above = 0.4
        below = 0.6
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 2.0
    [[effects.conditions]]
        groups = ["sugars"]
        match = "all"
        above = 0.6
        below = 0.8
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 4.0
    [[effects.conditions]]
        groups = ["sugars"]
        match = "all"
        above = 0.8
        below = 1.0
[[effects]]
    [[effects.status_effects]]
        name = "minecraft:regeneration"
        power = 0
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
        match = "all"
        above = 0.7
        below = 1.0