
#General settings
[general]
	#A list of buildings that are safe(r)
	excludedBuildings = ["multi_communitycenter_3", "multi_communitycenter_4", "multi_communitycenter_6", "multi_convenientstore_0", "multi_convenientstore_2", "multi_cafe_0", "multi_cafe_1", "multi_cafe_2", "multi_cafe_3", "multi_gallery_2"]
	#List of mobs that can spawn in buildings together with their rarity
	mobs = ["2.0=minecraft:zombie", ".4=undead_revamp2:thesmoker", ".2=undead_revamp2:the_moonflower", ".1=undead_revamp2:thepregnant"]
	#List of weapons that the mobs can have together with their rarity
	randomWeapons = ["2.5=null"]
	#List of helmets that the mobs can have together with their rarity
	randomHelmets = [".3=null"]
	#List of chestplates that the mobs can have together with their rarity
	randomChestplates = [".3=null"]
	#List of leggings that the mobs can have together with their rarity
	randomLeggings = [".3=null"]
	#List of boots that the mobs can have together with their rarity
	randomBoots = [".3=null"]
	#List of effects that a mob can have. Note that multiple effects are possible
	randomEffects = ["2.5=minecraft:regeneration,1", ".3=minecraft:speed,0", ".1=minecraft:speed,1"]
	#List of console commands to execute the first time a building is entered
	commandFirstTime = []
	#List of console commands to execute every time a building is entered
	commandEntered = []
	#List of console commands to execute when a building is cleared
	commandCleared = []
	#This message is given when the player tries to open a chest in a haunted building
	messageUnsafeBuilding = "The building isn't safe enough!"
	#This message is given when the player enters a haunted building for the first time
	messageBuildingHaunted = "building.haunted.enter"
	#This message is given when the player clears a building
	messageBuildingCleared = "building.haunted.cleared"
	#This message is given when the player is halfway clearing a building
	messageBuildingHalfway = "building.haunted.halfway"
	#The amount of ticks that the server waits before checking for new spawns
	#Range: 1 ~ 1000000
	serverTickTimeout = 5
	#The maximum amount of entities that can spawn near each other (of the same type)
	#Range: 1 ~ 200
	spawnMaxNearby = 10
	#The minimum distance between the player and newly spawned mobs
	#Range: 0.0 ~ 16.0
	minSpawnDistance = 9.0
	#The minimum health bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	minHealthBonus = 1.0
	#The maximum health bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	maxHealthBonus = 2.0
	#The minimum damage bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	minDamageBonus = 0.5
	#The maximum damage bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	maxDamageBonus = 1.0
	#The chance that a building is haunted
	#Range: 0.0 ~ 1.0
	hauntedChance = 0.15
	#The minimum amount of mobs that are spawned by a haunted building
	#Range: 1 ~ 10000
	minMobs = 10
	#The maximum amount of mobs that are spawned by a haunted building
	#Range: 1 ~ 10000
	maxMobs = 20
	#The chance that a building is haunted. This version is used in case the building is in a Lost City sphere
	#Range: 0.0 ~ 1.0
	sphereHauntedChance = 0.15
	#The minimum amount of mobs that are spawned by a haunted building. This version is used in case the building is in a Lost City sphere
	#Range: 1 ~ 10000
	sphereMinMobs = 10
	#The maximum amount of mobs that are spawned by a haunted building. This version is used in case the building is in a Lost City sphere
	#Range: 1 ~ 10000
	sphereMaxMobs = 50
	#If this is true then mobs will only spawn if the light level is low enough. Otherwise they spawn regardless of light level
	checkValidSpawn = true
	#If this is true then the player will be notified when a building is cleared
	announceCleared = true
	#If this is true then the player will be notified when he or she enters a haunted building
	announceEnter = true
	#If this is true then the player will get a message when he/she tries to open a locked chest
	announceChestLocked = true
	#If this is true then all chests will be locked until the building is cleared
	lockChestsUntilCleared = false
	#This option is only useful when 'lockChestsUntilCleared'. If true only vanilla chests will be locked. Otherwise all tile entities are locked
	lockOnlyChests = false
	#If this is true then mobs will only spawn on blocks but not on air
	spawnOnBlock = true
	#This message is given when the player enters a haunted building after at least 'messageInterval' ticks have passed. Use <same> to have the same message as the first time
	messageBuildingHauntedRepeat = "<same>"
	#The delay (in ticks) before a new 'haunted' message is given to the player
	#Range: 1 ~ 1000000
	messageInterval = 6000

