#This handles the coloring of food. Enter the color in DECIMAL format. Entering invalid format will default into black color.
foodBarColors = [16737380, 16777060, 9895780, 6592255, 16737535, 16777215]

